server:
  port: 8081

itis-capture:
 uri: http://localhost:5000
#spring:
# datasource:
#  driverClassName: com.mysql.jdbc.Driver
#  url: jdbcmysql://$(DB_HOST:localhost):3306/itis_prediction
#  username: root
#  password: root
#
# jpa:
#  database-platform:
#  org.hibernate.dialect.MySQLSDialect hibernate.ddl-auto: update
#  generate-ddl: true

spring:
 datasource:
  username: sa
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  password: password
 h2:
  console:
   enabled: 'true'
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect


 servlet:
  multipart:
   enabled: 'true'
   max-request-size: 215MB
   file-size-threshold: 2KB
   max-file-size: 200MB